[package]
name = "pbz-hash"
version = "0.1.0"
authors = ["Pebaz <pebazium@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meowhash = "0.1.3"
digest = "0.8.1"
hex = "0.3.1"
